version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    stdin_open: true
    tty: true
